# Generated by Django 4.2.9 on 2024-02-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iapp', '0002_bac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bac',
            new_name='Background',
        ),
    ]
